
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author a1094785
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    private final ArrayList<Jogador> tabela;


    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        this.tabela = new ArrayList<>(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janelaSelAbrir = new javax.swing.JFileChooser();
        janelaSelSalvar = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        caixaTxtNome = new javax.swing.JTextField();
        labelNum = new javax.swing.JLabel();
        caixaTxtNum = new javax.swing.JFormattedTextField();
        labelPos = new javax.swing.JLabel();
        caixaTxtPos = new javax.swing.JTextField();
        botaoLimpar = new javax.swing.JButton();
        botaoAdcionar = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        barraMenuArquivo = new javax.swing.JMenu();
        menuArqNovo = new javax.swing.JMenuItem();
        menuArqAbrir = new javax.swing.JMenuItem();
        menuArqSalvar = new javax.swing.JMenuItem();
        menuArqExibir = new javax.swing.JMenuItem();
        menuArqSair = new javax.swing.JMenuItem();

        janelaSelSalvar.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton1)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Jogadores");
        setName("janelaPrincipal"); // NOI18N
        setResizable(false);

        labelNome.setText("Nome do Jogador");

        caixaTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTxtNomeActionPerformed(evt);
            }
        });

        labelNum.setText("Número do Jogador");

        caixaTxtNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        caixaTxtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTxtNumActionPerformed(evt);
            }
        });

        labelPos.setText("Posição do Jogador");

        caixaTxtPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTxtPosActionPerformed(evt);
            }
        });

        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoAdcionar.setText("Adcionar");
        botaoAdcionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdcionarActionPerformed(evt);
            }
        });

        barraMenuArquivo.setText("Arquivo");

        menuArqNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuArqNovo.setText("Novo");
        barraMenuArquivo.add(menuArqNovo);

        menuArqAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuArqAbrir.setText("Abrir");
        menuArqAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArqAbrirActionPerformed(evt);
            }
        });
        barraMenuArquivo.add(menuArqAbrir);

        menuArqSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuArqSalvar.setText("Salvar");
        menuArqSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArqSalvarActionPerformed(evt);
            }
        });
        barraMenuArquivo.add(menuArqSalvar);

        menuArqExibir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuArqExibir.setText("Exibir");
        barraMenuArquivo.add(menuArqExibir);

        menuArqSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuArqSair.setText("Sair");
        barraMenuArquivo.add(menuArqSair);

        barraMenu.add(barraMenuArquivo);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caixaTxtPos)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(botaoAdcionar))
                    .addComponent(caixaTxtNome)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPos)
                            .addComponent(labelNome)
                            .addComponent(labelNum))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(caixaTxtNum))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaTxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaTxtPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoLimpar)
                    .addComponent(botaoAdcionar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdcionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdcionarActionPerformed
        // TODO add your handling code here:
        if(caixaTxtNum.getText() ==""   ||
           caixaTxtNome.getText() ==""  ||
           caixaTxtPos.getText() == ""  )
            
        tabela.add( new Jogador(
                Integer.parseInt(caixaTxtNum.getText()),
                caixaTxtNome.getText(),
                caixaTxtPos.getText()
        ));
    }//GEN-LAST:event_botaoAdcionarActionPerformed

    private void caixaTxtPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTxtPosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaTxtPosActionPerformed

    private void menuArqAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArqAbrirActionPerformed
        // TODO add your handling code here:
        janelaSelAbrir.showOpenDialog(this);
    }//GEN-LAST:event_menuArqAbrirActionPerformed

    private void caixaTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaTxtNomeActionPerformed

    private void menuArqSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArqSalvarActionPerformed
        // TODO add your handling code here:
        janelaSelSalvar.showSaveDialog(this);
    }//GEN-LAST:event_menuArqSalvarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        // TODO add your handling code here:
        caixaTxtNome.setText("");
        caixaTxtNum.setText("");
        caixaTxtPos.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void caixaTxtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTxtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaTxtNumActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu barraMenuArquivo;
    private javax.swing.JButton botaoAdcionar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JTextField caixaTxtNome;
    private javax.swing.JFormattedTextField caixaTxtNum;
    private javax.swing.JTextField caixaTxtPos;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser janelaSelAbrir;
    private javax.swing.JFileChooser janelaSelSalvar;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNum;
    private javax.swing.JLabel labelPos;
    private javax.swing.JMenuItem menuArqAbrir;
    private javax.swing.JMenuItem menuArqExibir;
    private javax.swing.JMenuItem menuArqNovo;
    private javax.swing.JMenuItem menuArqSair;
    private javax.swing.JMenuItem menuArqSalvar;
    // End of variables declaration//GEN-END:variables
}
